<?php
/**
 * 🚀 BOOTSTRAP FILE — Central initialization
 * ═════════════════════════════════════════════════
 * यो file सबै requests को शुरुमा load हुन्छ।
 * Database, Auth, Config, Helpers सबै यहाँ setup हुन्छ।
 * ═════════════════════════════════════════════════
 */

// ─────────────────────────────────────────────────
// 1. CORE CONFIGURATION
// ─────────────────────────────────────────────────

// Set error reporting
if (defined('ENVIRONMENT')) {
    if (ENVIRONMENT === 'development') {
        error_reporting(E_ALL);
        ini_set('display_errors', 1);
    } else {
        error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING);
        ini_set('display_errors', 0);
        ini_set('log_errors', 1);
    }
}

// Timezone
date_default_timezone_set('UTC');

// Character encoding
header('Content-Type: text/html; charset=utf-8');
mb_internal_encoding('UTF-8');

// ─────────────────────────────────────────────────
// 2. PATH DEFINITIONS
// ─────────────────────────────────────────────────

if (!defined('BASEDIR')) {
    define('BASEDIR', __DIR__);
}

if (!defined('INCLUDES_DIR')) {
    define('INCLUDES_DIR', BASEDIR . '/includes');
}

if (!defined('CONFIG_DIR')) {
    define('CONFIG_DIR', BASEDIR . '/config');
}

if (!defined('ADMIN_DIR')) {
    define('ADMIN_DIR', BASEDIR . '/admin');
}

if (!defined('MEMBER_DIR')) {
    define('MEMBER_DIR', BASEDIR . '/member');
}

if (!defined('ASSETS_DIR')) {
    define('ASSETS_DIR', BASEDIR . '/assets');
}

if (!defined('UPLOADS_DIR')) {
    define('UPLOADS_DIR', ASSETS_DIR . '/uploads');
}

if (!defined('DATABASE_DIR')) {
    define('DATABASE_DIR', BASEDIR . '/database');
}

// ─────────────────────────────────────────────────
// 3. DATABASE CONNECTION
// ─────────────────────────────────────────────────

// Check if database config exists
$dbConfigFile = INCLUDES_DIR . '/database.local.php';

if (file_exists($dbConfigFile)) {
    require_once $dbConfigFile;
} else {
    // Fallback to default config (should be generated by installer)
    // This prevents fatal error during initial setup
    if (!defined('ENVIRONMENT')) {
        define('ENVIRONMENT', 'production');
    }
    
    // Show setup message if not already in installation
    if (basename($_SERVER['PHP_SELF']) !== 'install.php' && 
        basename($_SERVER['PHP_SELF']) !== 'setup.php') {
        // Database not configured yet
        // Don't error here, let individual pages handle it
    }
}

// ─────────────────────────────────────────────────
// 4. LOAD CORE UTILITIES
// ─────────────────────────────────────────────────

// Helper functions
if (file_exists(INCLUDES_DIR . '/helpers.php')) {
    require_once INCLUDES_DIR . '/helpers.php';
}

// Authentication
if (file_exists(INCLUDES_DIR . '/auth.php')) {
    require_once INCLUDES_DIR . '/auth.php';
}

// Validation
if (file_exists(INCLUDES_DIR . '/validation.php')) {
    require_once INCLUDES_DIR . '/validation.php';
}

// ─────────────────────────────────────────────────
// 5. SITE CONFIGURATION
// ─────────────────────────────────────────────────

// Base URL
if (!defined('SITE_URL')) {
    $protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https://' : 'http://';
    $host = $_SERVER['HTTP_HOST'] ?? 'localhost';
    define('SITE_URL', $protocol . $host);
}

// Site root
if (!defined('SITE_ROOT')) {
    $scriptPath = dirname($_SERVER['SCRIPT_NAME']);
    define('SITE_ROOT', ($scriptPath === '/') ? '/' : $scriptPath . '/');
}

// ─────────────────────────────────────────────────
// 6. SESSION HANDLING
// ─────────────────────────────────────────────────

// Start session if not already started
if (session_status() === PHP_SESSION_NONE) {
    // Set secure session options
    $sessionOptions = [
        'use_strict_mode' => 1,
        'use_only_cookies' => 1,
        'cookie_httponly' => 1,
        'cookie_secure' => (!empty($_SERVER['HTTPS'])),
        'sid_length' => 48,
        'sid_bits_per_character' => 6,
    ];
    
    session_start($sessionOptions);
}

// Regenerate session ID for security on certain pages
if (!isset($_SESSION['session_created'])) {
    $_SESSION['session_created'] = time();
}

// ─────────────────────────────────────────────────
// 7. ERROR LOGGING
// ─────────────────────────────────────────────────

if (!function_exists('log_error')) {
    function log_error($message, $level = 'ERROR') {
        $logFile = BASEDIR . '/logs/error.log';
        
        // Ensure logs directory exists
        if (!is_dir(dirname($logFile))) {
            @mkdir(dirname($logFile), 0755, true);
        }
        
        $timestamp = date('Y-m-d H:i:s');
        $logEntry = "[{$timestamp}] [{$level}] {$message}\n";
        
        @error_log($logEntry, 3, $logFile);
    }
}

// ─────────────────────────────────────────────────
// 8. GLOBAL FUNCTIONS
// ─────────────────────────────────────────────────

if (!function_exists('get_site_setting')) {
    /**
     * Get site setting from database
     * Settings cached in session to reduce queries
     */
    function get_site_setting($key, $default = null) {
        global $pdo;
        
        // Check session cache first
        if (!isset($_SESSION['site_settings'])) {
            $_SESSION['site_settings'] = [];
        }
        
        if (isset($_SESSION['site_settings'][$key])) {
            return $_SESSION['site_settings'][$key];
        }
        
        // Query database
        try {
            if (isset($pdo)) {
                $stmt = $pdo->prepare('SELECT `value` FROM settings WHERE `key` = ? LIMIT 1');
                $stmt->execute([$key]);
                $result = $stmt->fetch();
                
                if ($result) {
                    $_SESSION['site_settings'][$key] = $result['value'];
                    return $result['value'];
                }
            }
        } catch (Exception $e) {
            log_error("Error fetching setting '{$key}': " . $e->getMessage());
        }
        
        return $default;
    }
}

if (!function_exists('set_site_setting')) {
    /**
     * Set site setting in database
     */
    function set_site_setting($key, $value) {
        global $pdo;
        
        try {
            if (isset($pdo)) {
                $stmt = $pdo->prepare(
                    'INSERT INTO settings (`key`, `value`, updated_at) 
                     VALUES (?, ?, NOW())
                     ON DUPLICATE KEY UPDATE `value` = VALUES(`value`), updated_at = NOW()'
                );
                $stmt->execute([$key, $value]);
                
                // Clear cache
                if (isset($_SESSION['site_settings'][$key])) {
                    unset($_SESSION['site_settings'][$key]);
                }
                
                return true;
            }
        } catch (Exception $e) {
            log_error("Error setting '{$key}': " . $e->getMessage());
        }
        
        return false;
    }
}

// ─────────────────────────────────────────────────
// 9. CUSTOM ERROR HANDLER
// ─────────────────────────────────────────────────

set_error_handler(function($errno, $errstr, $errfile, $errline) {
    log_error("PHP Error: {$errstr} in {$errfile} on line {$errline}", 'PHP');
    
    // Don't execute PHP internal error handler
    return true;
});

set_exception_handler(function($exception) {
    log_error("Exception: " . $exception->getMessage(), 'EXCEPTION');
    
    // Show error page or message
    if (defined('ENVIRONMENT') && ENVIRONMENT !== 'production') {
        throw $exception;
    } else {
        header($_SERVER['SERVER_PROTOCOL'] . ' 500 Internal Server Error', true, 500);
        include BASEDIR . '/500.php';
        exit;
    }
});

// ─────────────────────────────────────────────────
// 10. SECURITY HEADERS
// ─────────────────────────────────────────────────

// Prevent clickjacking
header('X-Frame-Options: SAMEORIGIN');

// Prevent MIME sniffing
header('X-Content-Type-Options: nosniff');

// Enable XSS protection
header('X-XSS-Protection: 1; mode=block');

// Referrer policy
header('Referrer-Policy: strict-origin-when-cross-origin');

// ═════════════════════════════════════════════════
// BOOTSTRAP COMPLETE
// ═════════════════════════════════════════════════
?>
